/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedBusinessIndexRouteImport } from './routes/_authenticated/business/index'
import { Route as AuthenticatedAgentIndexRouteImport } from './routes/_authenticated/agent/index'
import { Route as AuthenticatedStudentOrdersRouteImport } from './routes/_authenticated/student/orders'
import { Route as AuthenticatedStudentCartRouteImport } from './routes/_authenticated/student/cart'
import { Route as AuthenticatedBusinessProductsRouteImport } from './routes/_authenticated/business/products'
import { Route as AuthenticatedAgentActiveRouteImport } from './routes/_authenticated/agent/active'
import { Route as AuthenticatedStudentOrdersIdRouteImport } from './routes/_authenticated/student/orders.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/student/',
    path: '/student/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBusinessIndexRoute =
  AuthenticatedBusinessIndexRouteImport.update({
    id: '/business/',
    path: '/business/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentIndexRoute = AuthenticatedAgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentOrdersRoute =
  AuthenticatedStudentOrdersRouteImport.update({
    id: '/student/orders',
    path: '/student/orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentCartRoute =
  AuthenticatedStudentCartRouteImport.update({
    id: '/student/cart',
    path: '/student/cart',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBusinessProductsRoute =
  AuthenticatedBusinessProductsRouteImport.update({
    id: '/business/products',
    path: '/business/products',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentActiveRoute =
  AuthenticatedAgentActiveRouteImport.update({
    id: '/agent/active',
    path: '/agent/active',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentOrdersIdRoute =
  AuthenticatedStudentOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedStudentOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/agent/active': typeof AuthenticatedAgentActiveRoute
  '/business/products': typeof AuthenticatedBusinessProductsRoute
  '/student/cart': typeof AuthenticatedStudentCartRoute
  '/student/orders': typeof AuthenticatedStudentOrdersRouteWithChildren
  '/agent/': typeof AuthenticatedAgentIndexRoute
  '/business/': typeof AuthenticatedBusinessIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/student/orders/$id': typeof AuthenticatedStudentOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/agent/active': typeof AuthenticatedAgentActiveRoute
  '/business/products': typeof AuthenticatedBusinessProductsRoute
  '/student/cart': typeof AuthenticatedStudentCartRoute
  '/student/orders': typeof AuthenticatedStudentOrdersRouteWithChildren
  '/agent': typeof AuthenticatedAgentIndexRoute
  '/business': typeof AuthenticatedBusinessIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/student/orders/$id': typeof AuthenticatedStudentOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/agent/active': typeof AuthenticatedAgentActiveRoute
  '/_authenticated/business/products': typeof AuthenticatedBusinessProductsRoute
  '/_authenticated/student/cart': typeof AuthenticatedStudentCartRoute
  '/_authenticated/student/orders': typeof AuthenticatedStudentOrdersRouteWithChildren
  '/_authenticated/agent/': typeof AuthenticatedAgentIndexRoute
  '/_authenticated/business/': typeof AuthenticatedBusinessIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/student/orders/$id': typeof AuthenticatedStudentOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/profile'
    | '/wallet'
    | '/agent/active'
    | '/business/products'
    | '/student/cart'
    | '/student/orders'
    | '/agent/'
    | '/business/'
    | '/student/'
    | '/student/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/profile'
    | '/wallet'
    | '/agent/active'
    | '/business/products'
    | '/student/cart'
    | '/student/orders'
    | '/agent'
    | '/business'
    | '/student'
    | '/student/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/wallet'
    | '/_authenticated/agent/active'
    | '/_authenticated/business/products'
    | '/_authenticated/student/cart'
    | '/_authenticated/student/orders'
    | '/_authenticated/agent/'
    | '/_authenticated/business/'
    | '/_authenticated/student/'
    | '/_authenticated/student/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/business/': {
      id: '/_authenticated/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof AuthenticatedBusinessIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent/': {
      id: '/_authenticated/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AuthenticatedAgentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/orders': {
      id: '/_authenticated/student/orders'
      path: '/student/orders'
      fullPath: '/student/orders'
      preLoaderRoute: typeof AuthenticatedStudentOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/cart': {
      id: '/_authenticated/student/cart'
      path: '/student/cart'
      fullPath: '/student/cart'
      preLoaderRoute: typeof AuthenticatedStudentCartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/business/products': {
      id: '/_authenticated/business/products'
      path: '/business/products'
      fullPath: '/business/products'
      preLoaderRoute: typeof AuthenticatedBusinessProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent/active': {
      id: '/_authenticated/agent/active'
      path: '/agent/active'
      fullPath: '/agent/active'
      preLoaderRoute: typeof AuthenticatedAgentActiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/orders/$id': {
      id: '/_authenticated/student/orders/$id'
      path: '/$id'
      fullPath: '/student/orders/$id'
      preLoaderRoute: typeof AuthenticatedStudentOrdersIdRouteImport
      parentRoute: typeof AuthenticatedStudentOrdersRoute
    }
  }
}

interface AuthenticatedStudentOrdersRouteChildren {
  AuthenticatedStudentOrdersIdRoute: typeof AuthenticatedStudentOrdersIdRoute
}

const AuthenticatedStudentOrdersRouteChildren: AuthenticatedStudentOrdersRouteChildren =
  {
    AuthenticatedStudentOrdersIdRoute: AuthenticatedStudentOrdersIdRoute,
  }

const AuthenticatedStudentOrdersRouteWithChildren =
  AuthenticatedStudentOrdersRoute._addFileChildren(
    AuthenticatedStudentOrdersRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedAgentActiveRoute: typeof AuthenticatedAgentActiveRoute
  AuthenticatedBusinessProductsRoute: typeof AuthenticatedBusinessProductsRoute
  AuthenticatedStudentCartRoute: typeof AuthenticatedStudentCartRoute
  AuthenticatedStudentOrdersRoute: typeof AuthenticatedStudentOrdersRouteWithChildren
  AuthenticatedAgentIndexRoute: typeof AuthenticatedAgentIndexRoute
  AuthenticatedBusinessIndexRoute: typeof AuthenticatedBusinessIndexRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedAgentActiveRoute: AuthenticatedAgentActiveRoute,
  AuthenticatedBusinessProductsRoute: AuthenticatedBusinessProductsRoute,
  AuthenticatedStudentCartRoute: AuthenticatedStudentCartRoute,
  AuthenticatedStudentOrdersRoute: AuthenticatedStudentOrdersRouteWithChildren,
  AuthenticatedAgentIndexRoute: AuthenticatedAgentIndexRoute,
  AuthenticatedBusinessIndexRoute: AuthenticatedBusinessIndexRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
